

help: 0
achievement: 5
ban: 999
ban-ip: 999
banlist: 0
blockdata: 10
clear: 5
clone: 10
debug: 1
defaultgamemode: 999
deop: 999
difficulty: 3
effect: 5
enchant: 3
entitydata: 3
execute: -2
fill: -1
gamemode: -3
gamerule: 1
give: -1
kick: 3
kill: 10
list: 0
local: 5
me: 0
msg: 0
op: 999
pardon: 999
pardon-ip: 999
particle: 1
playsound: 2
replaceitem: 7
save-all: 1
save-off: 999
save-on: 1
say: 0
scoreboard: 5
seed: 30
setblock: 10
setidletimeout: 5
spawnpoint: 5
spreadplayers: 10
stop: 999
summon: 15
teleport: 15
tell: 0
tellraw: 0
testfor: 1
testforblock: 1
time: 2
title: 2
toggledownfall: 1
tp: 15
trigger: 3
w: 0
weather: 3
ehitelist: 10
worldborder: 15
xp: 10